streamConfig:
  responseHeaders:
    -
      pathPattern: *
      headerKey: joe-custom-header
      headerValues:
        -
          joe-custom-value

ciConfig:
  buildArtifacts:
    buildCmd: echo "foo"